running:
  model_type: onnx
  export: True
  inference: True
  eval_perf: False


parameters:
  onnx:
    model: '/WORK/MODEL/depth/monodepth/SC-Depth/D8.0.24/epoch=283-val_loss=0.1280.onnx'

config:
  mean_values: [[0.45, 0.45, 0.45]] # 123.675 116.28 103.53 58.395 # 0 0 0 255
  std_values: [[0.225, 0.225, 0.225]]
#  quant_img_RGB2BGR: True # '2 1 0' # '0 1 2' '2 1 0'
  target_platform: 'rk3566'
  quantized_dtype: 'asymmetric_quantized-8' # asymmetric_quantized-u8,dynamic_fixed_point-8,dynamic_fixed_point-16
  optimization_level: 1

build:
  do_quantization: True
  dataset: 'single_dataset.txt'

export_rknn:
  export_path: '/WORK/MODEL/depth/monodepth/SC-Depth/D8.0.24/epoch=283-val_loss=0.1280.rknn'

init_runtime:
  target: null
  device_id: null
  perf_debug: False
  eval_mem: False
  async_mode: False

img: &img
  path: './bus.jpg'

inference:
  inputs: *img
  data_type: 'uint8'
  data_format: 'nhwc' # 'nchw', 'nhwc'
  inputs_pass_through: None 

eval_perf:
  inputs: *img
  data_type: 'uint8'
  data_format: 'nhwc'
  is_print: True




